<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="INMUVADP014584" failures="1" tests="1" name="Runner.TestApplication" time="35.507" errors="0" timestamp="2022-08-25T15:00:13 IST" skipped="0">
  <testcase classname="Runner.TestApplication" name="runScenario" time="35.507">
    <failure message="expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at org.testng.Assert.assertFalse(Assert.java:77)
at stepdefinitions.ULS_ReportMasterSteps.verify_system_should_not_allow_user_to_save_the_parameter_details_record(ULS_ReportMasterSteps.java:450)
at âœ½.verify system should not allow user to save the parameter details record(file:///C:/Users/inindc00076/git/KULS_Anandh/AzentioULSFramework_Anandh/src/test/java/features/ULS_ReportMasterFeature.feature:36)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- Runner.TestApplication -->
